?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>ve-hotel-link-data</artifactId>
        <groupId>cn.vetech.center</groupId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <groupId>cn.vetech.center</groupId>
    <artifactId>ve-hotel-link-outface</artifactId>
    <version>1.0-SNAPSHOT</version>

    <name>ve-hotel-link-outface</name>
    <dependencies>
        <dependency>
            <groupId>cn.vetech.center</groupId>
            <artifactId>ve-hotel-link-api</artifactId>
            <version>${ve-hotel-link-data.version}</version>
        </dependency>
        <dependency>
            <groupId>cn.vetech.center</groupId>
            <artifactId>ve-hotel-link-common</artifactId>
            <version>${ve-hotel-link-data.version}</version>
        </dependency>
        <dependency>
            <groupId>cn.vetech.charge.cloud</groupId>
            <artifactId>charge-cloud-springcloud</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.vetech.center</groupId>
            <artifactId>mapping-hotel-api</artifactId>
            <version>${mapping-hotel-api.version}</version>
        </dependency>
        <dependency>
            <groupId>cn.vetech.center</groupId>
            <artifactId>mapping-hotel-domain</artifactId>
            <version>${mapping-hotel-domain.version}</version>
        </dependency>
        <dependency>
            <groupId>cn.vetech.center</groupId>
            <artifactId>price-hotel-domain</artifactId>
        </dependency>

    </dependencies>
</project>
